model:
  id: unsloth/gpt-oss-20b-BF16
  dtype: float32
  device: cpu
  max_new_tokens: 200
  temperature: 0.3
  do_sample: true
  max_seq_length: 2048
  load_in_4bit: false
  load_in_8bit: false
embeddings:
  model_name: sentence-transformers/all-MiniLM-L6-v2
  device: mps
vector_store:
  index_dir: data/faiss_store
  chunk_size: 1000
  chunk_overlap: 150
  top_k: 4
paths:
  pdf_dir: data/science_pdfs
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
ui:
  show_spinner: true
  system_prompt: 'You are an expert biomechanics assistant.

    Answer concisely and cite supporting chunks like [1], [2].

    Do not reveal your internal analysis or reasoning steps.

    '
tts:
  device: mps
  exaggeration: 0.5
  cfg_weight: 0.5
  output_dir: data/tts_output
  enabled: false
  auto_play: false
