# Configuration file for RAG application
model:
  id: "unsloth/gpt-oss-20b-BF16"
  dtype: "bfloat16"
  device: "mps"
  max_new_tokens: 512
  temperature: 0.7
  do_sample: true

embeddings:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  device: "mps"  # Use "cpu" to save GPU memory

vector_store:
  index_dir: "data/faiss_store"
  chunk_size: 1000
  chunk_overlap: 150
  top_k: 4

paths:
  pdf_dir: "data/science_pdfs"
  
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
ui:
  show_spinner: true
  system_prompt: |
    You are an expert biomechanics assistant.
    Answer concisely and cite supporting chunks like [1], [2].
    Do not reveal your internal analysis or reasoning steps.