embeddings:
  device: mps
  model_name: sentence-transformers/all-MiniLM-L6-v2
logging:
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
model:
  device: cpu
  do_sample: true
  dtype: float32
  id: unsloth/gpt-oss-20b-BF16
  load_in_4bit: false
  load_in_8bit: false
  max_new_tokens: 100
  max_seq_length: 2048
  temperature: 0.3
paths:
  pdf_dir: data/science_pdfs
tts:
  auto_play: false
  cfg_weight: 0.5
  device: mps
  enabled: false
  exaggeration: 0.5
  output_dir: data/tts_output
ui:
  show_spinner: true
  system_prompt: 'You are an expert biomechanics assistant.

    Answer concisely and cite supporting chunks like [1], [2].

    Do not reveal your internal analysis or reasoning steps.

    '
vector_store:
  chunk_overlap: 150
  chunk_size: 1000
  index_dir: data/faiss_store
  top_k: 4
